ideascube/search/urls.py
from django.conf.urls import url

from . import views


app_name = 'search'
urlpatterns = [
    url(r'^$', views.search, name='search'),
]

ideascube/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog


from . import views

urlpatterns = i18n_patterns(
    url(r'^blog/', include('ideascube.blog.urls')),
    url(r'^library/', include('ideascube.library.urls')),
    url(r'^search/', include('ideascube.search.urls')),
    url(r'^mediacenter/', include('ideascube.mediacenter.urls')),
    url(r'^monitoring/', include('ideascube.monitoring.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^welcome_staff/$', views.welcome_staff, name='welcome_staff'),
    url(r'^server/', include('ideascube.serveradmin.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={"next_page": "/"},
        name='logout'),
    url(r'^user/$', views.user_list, name='user_list'),
    url(r'^user/(?P<pk>[\d]+)/$', views.user_detail, name='user_detail'),
    url(r'^user/(?P<pk>[\d]+)/edit/$', views.user_update, name='user_update'),
    url(r'^user/(?P<pk>[\d]+)/set-password/$', views.set_password,
        name='user_set_password'),
    url(r'^user/new/$', views.user_create, name='user_create'),
    url(r'^user/export/$', views.user_export, name='user_export'),
    url(r'^user/import/$', views.user_import, name='user_import'),
    url(r'^user/(?P<pk>[\d]+)/delete/$',
        views.user_delete, name='user_delete'),
    url(r'^user/(?P<pk>[\d]+)/toggle-staff/$',
        views.user_toggle_staff, name='user_toggle_staff'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['ideascube']), name='jsi18n'),
)
urlpatterns = urlpatterns + [
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ideascube/search/models.py
from django.db import models
from django.db.backends.signals import connection_created
from django.db.models.signals import post_save, pre_delete
from django.db.models.base import ModelBase
from django.dispatch import receiver

from .utils import rank
from ..utils import MetaRegistry


class Match(models.Lookup):
    lookup_name = 'match'

    def as_sql(self, qn, connection):
        lhs, lhs_params = self.process_lhs(qn, connection)
        rhs, rhs_params = self.process_rhs(qn, connection)
        params = lhs_params + rhs_params
        return '{0} MATCH {1}'.format(lhs, rhs), params


class SearchField(models.Field):
    pass
SearchField.register_lookup(Match)


class TagMatch(models.Lookup):
    lookup_name = 'match'

    def as_sql(self, qn, connection):
        lhs, lhs_params = self.process_lhs(qn, connection)
        rhs, rhs_params = self.process_rhs(qn, connection)
        params = lhs_params + rhs_params
        params = params[0]
        if not params:
            # Not tags to match to.
            # Search for stuff with no tag
            params = ['']
        out = '({0} LIKE {1})'.format(lhs, rhs)
        out = ' AND '.join([out]*len(params))
        out = '({})'.format(out)
        return out, ['%|{}|%'.format(p.lower()) for p in params]


class SearchTagField(models.Field):
    pass
SearchTagField.register_lookup(TagMatch)


class SearchQuerySet(models.QuerySet):
    def order_by_relevancy(self):
        extra = {'relevancy': 'rank(matchinfo(idx))'}
        return self.extra(select=extra).order_by('-relevancy')


class Search(models.Model):
    """Model that handle the search."""
    rowid = models.IntegerField(primary_key=True)
    model = models.CharField(max_length=64)
    object_id = models.IntegerField()
    public = models.BooleanField(default=True)
    text = SearchField()
    lang = models.Field()
    kind = models.Field()
    tags = SearchTagField()
    source = models.Field()

    objects = SearchQuerySet.as_manager()

    class Meta:
        db_table = 'idx'
        managed = False

    @classmethod
    def ids(cls, **kwargs):
        qs = Search.objects.filter(**kwargs).order_by_relevancy()
        return qs.values_list('object_id', flat=True)

    @classmethod
    def search(cls, **kwargs):
        qs = Search.objects.filter(**kwargs).order_by_relevancy()
        return (SearchMixin.registered_types[r.model].objects.get(pk=r.object_id) for r in qs)


class MetaSearchMixin(MetaRegistry, ModelBase):
    pass


class SearchMixin(models.Model, metaclass=MetaSearchMixin):
    """Inherit from this mixin to make your model searchable."""

    class Meta:
        abstract = True

    @property
    def index_strings(self):
        return []

    @property
    def index_lang(self):
        return None

    @property
    def index_kind(self):
        return None

    @property
    def index_tags(self):
        return []

    @property
    def index_public(self):
        return True

    @property
    def index_source(self):
        return None

    def is_indexable(self):
        return True

    def index(self):
        if not self.is_indexable():
            return
        text = u" ".join([s for s in self.index_strings if s])
        tags = u"|{}|".format(u"|".join(self.index_tags))
        defaults = {
            'text': text,
            'public': self.index_public,
            'lang': self.index_lang,
            'kind': self.index_kind,
            'source': self.index_source,
            'tags': tags
        }
        Search.objects.update_or_create(
            model=self.__class__.__name__,
            object_id=self.pk,
            defaults=defaults
        )

    def deindex(self):
        Search.objects.filter(
            model=self.__class__.__name__,
            object_id=self.pk).delete()


class SearchableQuerySet(object):
    def search(self, query=None, kind=None, lang=None, tags=[], source=None, **kwargs):
        kwargs['model'] = self.model.__name__
        if query:
            kwargs['text__match'] = query
        if kind:
            kwargs['kind'] = kind
        if lang:
            kwargs['lang'] = lang
        if source:
            kwargs['source'] = source
        if tags:
            kwargs['tags__match'] = tags
        ids = Search.ids(**kwargs).distinct()
        # Force the execution of the request here
        # as we can request on several db in the same time.
        ids = list(ids)
        return self.filter(pk__in=ids)


@receiver(post_save)
def index(sender, instance, **kwargs):
    if issubclass(sender, SearchMixin):
        instance.index()


@receiver(pre_delete)
def deindex(sender, instance, **kwargs):
    if issubclass(sender, SearchMixin):
        instance.deindex()


@receiver(connection_created)
def add_rank_function(sender, connection, **kwargs):
    connection.connection.create_function("rank", 1, rank)

ideascube/search/views.py
from django.shortcuts import render

from .models import SearchMixin


def search(request):
    query = request.GET.get('q', '')
    results = []
    if query:
        search_kwargs = {'text__match': query}
        if not request.user.is_staff:
            search_kwargs['public'] = True
        for model in SearchMixin.registered_types.values():
            results.extend(model.objects.search(**search_kwargs))
    context = {
        'results': results,
        'q': query
    }
    return render(request, 'search/search.html', context)

ideascube/search/templates/search/box.html
{% load i18n %}

{% spaceless %}
<div class="card tinted search">
    <form action="{% if action %}{{ action }}{% else %}{% url "search:search" %}{% endif %}" id="search">
        <input name="q" type="text" placeholder="{% trans 'search' %}" value="{{ q|default:'' }}" />
        {% for key, value in current_filters %}
            <input name="{{ key }}" type="hidden" value="{{ value }}" />
        {% endfor %}
        <input type="submit" value="{% trans 'search' %}" />
    </form>
</div>
{% endspaceless %}

ideascube/search/templates/search/filter_by_kind.html
{% load i18n ideascube_tags %}
{% if available_kinds %}
<div class="card tinted">
    <h4><span class="theme discover">{% trans "browse" %}</span> {% if title %}{{ title }}{% else %}{% trans 'by kind' %}{% endif %}</h4>
    {% for kind, label in available_kinds %}
        {% is_in_qs 'kind' kind as in_qs %}
        {% if in_qs %}
            <a href="{% remove_qs kind=kind %}" class="flatlist active">{{ label }}</a>
        {% else %}
            <a href="{% replace_qs kind=kind %}" class="flatlist">{{ label }}</a>
        {% endif %}
    {% endfor %}
</div>
{% endif %}

ideascube/search/templates/search/filter_by_lang.html
{% load i18n ideascube_tags %}
{% if available_langs %}
<div class="card tinted">
    <h4><span class="theme discover">{% trans "browse" %}</span> {% trans 'by language' %}</h4>
    {% for lang, label in available_langs %}
        {% is_in_qs 'lang' lang as in_qs %}
        {% if in_qs %}
            <a href="{% remove_qs lang=lang %}" class="flatlist active">{{ label|capfirst }}</a>
        {% else %}
            <a href="{% replace_qs lang=lang %}" class="flatlist">{{ label|capfirst }}</a>
        {% endif %}
    {% endfor %}
</div>
{% endif %}

ideascube/search/templates/search/filter_cloud.html
{% load i18n ideascube_tags %}
{% spaceless %}
{% if q or kind or lang or tags or source %}
  <div class="filters card tinted">
    <h4>{% trans "Filters" %}</h4>
    <ul>
      {% if q %}
        <li>
          <a href="{% remove_qs q=q %}">
            {{ q }}
            <i class="fa fa-close"></i>
          </a>
        </li>
      {% endif %}
      {% if kind %}
        <li>
          <a href="{% remove_qs kind=kind %}">
            {{ view.model.KIND_DICT|getitem:kind }}
            <i class="fa fa-close"></i>
          </a>
        </li>
      {% endif %}
      {% if lang %}
        {% with LANG_INFO|getitem:lang as lang_info %}
          <li>
            <a href="{% remove_qs lang=lang %}">
              {{ lang_info.name_local }}
            <i class="fa fa-close"></i>
            </a>
          </li>
        {% endwith %}
      {% endif %}
      {% if source %}
          <li>
            <a href="{% remove_qs source=source %}">
              {{ source_name }}
            <i class="fa fa-close"></i>
            </a>
          </li>
      {% endif %}
      {% for t in tags %}
        <li>
          <a href="{% remove_qs tags=t %}">
            {{ t|tag_name }}
            <i class="fa fa-close"></i>
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endif %}
{% endspaceless %}

ideascube/search/templates/search/order_by.html
{% load i18n ideascube_tags %}
{% if view.ORDERS %}
<div class="card tinted">
    <h4>{% trans "Order by" %}</h4>
    {% for order in view.ORDERS %}
        {% if order_by == order.key %}
            {% if sort == 'asc' %}
                <a href="{% replace_qs order_by=order.key sort='desc' %}" class="flatlist active">{% fa 'arrow-up' %} {{ order.label }}</a>
            {% else %}
                <a href="{% replace_qs order_by=order.key sort='asc' %}" class="flatlist active">{% fa 'arrow-down' %} {{ order.label }}</a>
            {% endif %}
        {% else %}
            <a href="{% replace_qs order_by=order.key sort=order.sort %}" class="flatlist">{{ order.label }}</a>
        {% endif %}
    {% endfor %}
</div>
{% endif %}

ideascube/search/templates/search/search.html
{% extends 'base.html' %}
{% load i18n ideascube_tags %}

{% block body_class %}search{% endblock %}

{% block content %}
    <div class="row main">
        <div class="col two-third">
            <h2>{% trans 'Search in the box' %}</h2>
            {% include 'search/box.html' %}
            <ul class="results">
                {% if q %}
                    {% for result in results %}
                        <li>{{ result|theme_slug }} <a href="{{ result.get_absolute_url }}">{{ result }}</a></li>
                    {% empty %}
                        {% blocktrans with query=q %}No result for "{{ query }}".{% endblocktrans %}
                    {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock content %}